"""
Loads risk data from the precomputed lookup table (contracts/risk-lookup-table-format.md).

DECISION (this build): real data from Pair 1 will not arrive in time. We are
shipping on synthetic data generated by data-pipeline/generate_synthetic_lookup.py,
and treating it as the actual dataset for this build — not a placeholder.

If real data DOES arrive later: drop the real file at the same path
(data/processed/risk_lookup_<ward_id>.json), in the shape defined by
contracts/risk-lookup-table-format.md. Nothing in this file changes.
That's the entire point of this design — swap the file, not the code.
"""

import json
from pathlib import Path
from typing import Optional

_LOOKUP_DIR = Path(__file__).parent.parent / "data" / "processed"
_cache: dict[str, dict] = {}  # ward_id -> parsed file contents, loaded once per process

# Ward center coordinates, used by routing.py to build its road graph.
# Add an entry here for any ward you generate a lookup table for.
WARD_CENTERS = {
    "koramangala": (77.627, 12.935),
    "bellandur": (77.678, 12.926),
    "yelahanka": (77.596, 13.100),
}


def _load_ward_file(ward_id: str) -> Optional[dict]:
    if ward_id in _cache:
        return _cache[ward_id]

    path = _LOOKUP_DIR / f"risk_lookup_{ward_id}.json"
    if not path.exists():
        return None

    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        print(f"WARNING: {path.name} is not valid JSON ({e}). "
              f"Run: python data-pipeline/generate_synthetic_lookup.py {ward_id}")
        return None

    if "timesteps" not in data or not isinstance(data["timesteps"], dict):
        print(f"WARNING: {path.name} is missing a valid 'timesteps' object. "
              f"Check contracts/risk-lookup-table-format.md for the expected shape.")
        return None

    _cache[ward_id] = data
    return data


def _nearest_timestep(available: list[str], requested: str) -> str:
    """
    The frontend may ask for a timestamp that doesn't exactly match one of
    the precomputed steps. Snap to the closest available one rather than
    returning nothing.

    Real pipeline output (05_build_lookup.py) writes NAIVE timestamps (no
    timezone), while this codebase generates timezone-AWARE ones by default
    (datetime.now(timezone.utc)). Comparing the two directly raises
    TypeError - confirmed by running this against the actual real
    risk_lookup_koramangala.json. Strip timezone info from both sides
    before comparing so either format works.
    """
    from datetime import datetime

    def parse_naive(ts):
        return datetime.fromisoformat(ts).replace(tzinfo=None)

    target = parse_naive(requested)
    return min(available, key=lambda ts: abs((parse_naive(ts) - target).total_seconds()))


def get_risk_segments(ward_id: str, timestamp: str):
    """
    Returns the list of risk segments for a ward at (the nearest precomputed
    timestep to) the given timestamp, or None if no lookup file exists for
    that ward — in which case main.py returns a 404. There is no further
    fallback: a missing file means the ward genuinely isn't set up yet, and
    that should be visible, not silently papered over.
    """
    ward_id = ward_id.lower()
    file_data = _load_ward_file(ward_id)
    if file_data is None:
        return None

    available_timestamps = list(file_data["timesteps"].keys())
    if not available_timestamps:
        return None

    nearest = _nearest_timestep(available_timestamps, timestamp)
    return file_data["timesteps"][nearest]


def get_flood_points(ward_id: str):
    """
    Real, known flood-prone locations (not synthetic) - static list, no
    timesteps. Complementary to get_risk_segments(), not a replacement:
    this answers "where has flooding actually happened historically,"
    the risk lookup answers "how flooded will this street be right now."
    """
    path = _LOOKUP_DIR / f"flood_points_{ward_id.lower()}.geojson"
    if not path.exists():
        return None

    data = json.loads(path.read_text())
    return data.get("features", [])


def known_wards() -> list[str]:
    """Every ward with an actual lookup file on disk."""
    if not _LOOKUP_DIR.exists():
        return []
    return sorted(p.stem.replace("risk_lookup_", "") for p in _LOOKUP_DIR.glob("risk_lookup_*.json"))
